### ISSUE TITLE
你好，部署后报错

### ISSUE THREAD

**Issue by beer-on-ice** [kailous/RainForest-Notion-Nav#1]
![image](https://github.com/kailous/RainForest-Notion-Nav/assets/25942344/69ce09e9-e4a3-47fe-8f8c-069249d6dbb8)
报错，如图

**Comment by beer-on-ice** [comment]
![image](https://github.com/kailous/RainForest-Notion-Nav/assets/25942344/bc44bcb2-cf7d-4440-8ed8-a39dfce5641f)
已经解决，连接处选择添加的继承就能读取到了！

**Comment by muziyinlee** [comment]
大佬有没有详细教程啊！vercel部署的时候，直接在变量添加了以下三个变量，notion的链接处也添加好了！
NOTION_API_KEY: 
DATABASE_ID: 
NAV_NAME: 
但是部署成功后，打开页面就提示Application error: a client-side exception has occurred (see the browser console for more information).，弄了半天还是不行，不知道是哪个环节错了
