### ISSUE TITLE
想请问下你的图标是从哪下的？

### ISSUE THREAD

**Issue by Zephon-H** [kailous/RainForest-Notion-Nav#4]
想请问下你的各种icon图标是从哪下的？我自己下的有的会报错

**Comment by kailous** [comment]
自己制作的svg

**Comment by leslieyin** [comment]
> 想请问下你的各种icon图标是从哪下的？我自己下的有的会报错

偷偷给你分享一个  https://icon.yukonga.top/

**Comment by kailous** [comment]
我的图标 都是自制的图标 目前只能本地上传到 notion 数据库中 很多网站图标都是 png的，并且尺寸上大小不一，考虑视觉效果，我都是重绘的svg。可以无损放大，效果更好些。
