### ISSUE TITLE
图标只能从本地上传吗

### ISSUE THREAD

**Issue by leslieyin** [kailous/RainForest-Notion-Nav#5]
您好大佬，请问下图标只能从本地上传吗？我试了下添加图片link ，同步数据后报错了

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by kailous** [comment]
https://github.com/kailous/RainForest-Notion-Nav/issues/4#issuecomment-2101907817
你可以看这个
