### ISSUE TITLE
可以增加个详情页嘛，而不是点击直接跳转别人的网站

### ISSUE THREAD

**Issue by xinkeji** [kailous/RainForest-Notion-Nav#6]

**Comment by kailous** [comment]
这个加倒是可以加
但是不加这个功能有2个理由
这个是一个导航站 不是推广站 还是快速到达更好些
其二就是很重要的性能问题，为了更保证在vercel 上运行且实时更新notion 数据库的变化，限制了缓存的，如果这时候每次还要进详情页那么进出的页面刷新体验感会非常差。

如果需要详情页的那种，建议还是用 其他的建站工具。而不是考虑 基于 notion api
