### ISSUE TITLE
能不能给个notion的模板？

### ISSUE THREAD

**Issue by K1314047** [kailous/RainForest-Notion-Nav#7]
能不能给个notion的模板啊？我自己做的模板部署上去不显示啊

**Comment by kailous** [comment]
https://www.notion.so/bc70befb9e3341e89890e659dcc56673?v=b942cafbdfd248b8b90c919ebc87830b&pvs=4

**Comment by K1314047** [comment]
已发访问请求，请批准 谢谢大佬

**Comment by K1314047** [comment]
![捕获](https://github.com/user-attachments/assets/843f42ff-3ec2-4fb3-a6cb-b4d864dd9dd5)
大佬  有权限，已发访问请求，请批准
